---
title: snahelper - 'RStudio' Addin for Network Analysis and Visualization
format:
  html:
    embed-resources: true
  gfm: default
---

## Description

<!-- - Provide a brief and clear description of the method, its purpose, and what it aims to achieve. Add a link to a related paper from social science domain and show how your method can be applied to solve that research question.   -->

'RStudio' addin which provides a GUI to visualize and analyse networks. 
After finishing a session, the code to produce the plot is inserted in the current script.
Alternatively, the function SNAhelperGadget() can be used directly from the console.
Additional addins include the Netreader() for reading network files, Netbuilder() to create
small networks via point and click, and the Componentlayouter() to layout networks with many components manually.

## Keywords

<!-- EDITME -->

* Network Analysis
* Network Visualization

## Science Usecase(s)

Network analysis provides researchers with a versatile framework for examining relationships and structures within complex social systems. 
For example, in studying the dynamics of an online support community, one could use network analysis to explore how individuals connect, 
share resources, and offer support. By analyzing metrics such as degree centrality (identifying key individuals who connect others), 
clustering coefficients (revealing tightly-knit groups), and betweenness centrality (spotlighting users who bridge subgroups), researchers 
can understand how information and support flow within the community. This approach can uncover subgroups that form around 
shared needs, as well as highlight key figures who facilitate support or knowledge sharing. 
Network analysis also enables researchers to track changes in the community over time, such as the emergence of new
leaders or the diffusion of helpful resources, offering a better understanding of social cohesion, influence, and resilience 
within the community.

## Repository structure

This repository follows [the standard structure of an R package](https://cran.r-project.org/doc/FAQ/R-exts.html#Package-structure).

## Environment Setup

With R installed:

```r
install.packages("snahelper")
```

## Hardware Requirements

Snahelper runs on any machine that can run R.

## Input Data 

`snahelper` accepts `igraph` network objects.

## How to Use

The package provides a GUI as a RStudi addin which allows to produce a network visualization (and an analysis) via dropdown menus.
At the end of a session, the code to reproduce the results are returned for reproducibility.

## Technical Details

Check the official [CRAN page](https://doi.org/10.32614/CRAN.package.snahelper) for further information.

## Contact Details

Maintainer: David Schoch <david@schochastics.net>

Issue Tracker: [https://github.com/schochastics/snahelper/issues](https://github.com/schochastics/snahelper/issues)

<!-- ## Publication -->
<!-- - Include information on publications or articles related to the method, if applicable. -->

<!-- ## Acknowledgements -->
<!-- - Acknowledgements if any -->

<!-- ## Disclaimer -->
<!-- - Add any disclaimers, legal notices, or usage restrictions for the method, if necessary. -->
